[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[profile.remappings]
"@openzeppelin/=" = "lib/openzeppelin-contracts/contracts/"
"@chainlink/=" = "lib/chainlink/contracts/"

"@VRFConsumerBaseV2" ="lib/chainlink/contracts/src/v0.8/vrf/VRFConsumerBaseV2.sol"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
